### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by pololoko111**

### CODE REVIEW

**Comment by nickersk** [comment]
Thank You!

**Comment by oerlgrey** [comment]
Hi guys, thanks for your works!
Sorry for my time out.
I would now like to combine Python2 and Python3 and differentiate in the codes.
I've already prepared quite a bit.

**Comment by oerlgrey** [comment]
Hm, maybe it's not a good idea to combine.

**Comment by pololoko111** [comment]
Maybe it is worth focusing only on Py3.
Your skin works very well on Py2.
Most people already use Py3 images and are waiting for skin to be up-to-date with the changes taking place in Py3 images.

**Comment by oerlgrey** [comment]
Yes, that's how we do it.

**Pull request merged**
